language: python
python:
    - "3.6"      # current default Python on Travis CI
    - "3.7"
    - "3.8"
services:
    - docker
before_install:
    - docker pull igormcsouza/movie-review-plus-package:test
script:
    - docker run igormcsouza/movie-review-plus-package:test python -c "import classifier"